[package]
name = "advent-of-code-2015"
version = "0.1.0"
edition = "2021"

[dependencies]
input_loader = { path = "../input_loader" }

[[bin]]
name = "2015-01a"
path = "src/01a.rs"

[[bin]]
name = "2015-01b"
path = "src/01b.rs"

[[bin]]
name = "2015-02a"
path = "src/02a.rs"

[[bin]]
name = "2015-02b"
path = "src/02b.rs"

[[bin]]
name = "2015-03a"
path = "src/03a.rs"

[[bin]]
name = "2015-03b"
path = "src/03b.rs"
